---
- name: Init Kubernetes Master
  hosts: master[0]
  tasks:
    - name: Initialize Kubernetes control plane
      ansible.builtin.command: "sudo kubeadm init --control-plane-endpoint={{ hostvars[groups['floating_ip'][0]]['ansible_host'] }}:6443 --upload-certs --pod-network-cidr=10.244.0.0/16 --v=5"
      args:
        creates: /etc/kubernetes/admin.conf
      register: kubeadm_init
      become: yes

    - name: Create kube config directory
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.kube"
        state: directory
        mode: "0700"

    - name: Register kube config directory path
      ansible.builtin.shell: echo "{{ ansible_env.HOME }}/.kube"
      register: kube_config_dir

    - name: Copy kube config file
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: "{{ kube_config_dir.stdout }}/config"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0600"
        remote_src: true
      become: yes
      become_user: root

    - name: Get Kubernetes nodes
      ansible.builtin.command: kubectl get nodes -o wide
      register: nodes_details

    - name: Install Flannel
      ansible.builtin.command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
      register: flannel_apply
