- name: Generate and Execute Worker Join Token
  hosts: master[0]
  gather_facts: false
  become: true

  tasks:
    - name: Generate Worker Join Token
      command: kubeadm token create --print-join-command
      register: worker_join_token

    - name: Set fact for Worker Join Token
      set_fact:
        worker_join_command: "{{ worker_join_token.stdout_lines[0] }}"

- name: Execute Worker Join Command on Workernodes
  hosts: worker
  become: true
  become_user: root
  tasks:
    - name: Join Worker Node to Cluster
      command: "{{ hostvars[groups['master'][0]]['worker_join_command'] }}"
